---
default: true
first-header-h1: true
header-style:
  style: "atx"
ul-style:
  style: "dash"
no-trailing-spaces: false
line-length: false
no-duplicate-header:
  allow_different_nesting: true
no-trailing-punctuation:
  punctuation: ".,;:!。，；：！？"
ol-prefix:
  style: "one"
no-inline-html: false
hr-style:
  style: "---"
no-emphasis-as-heading: false
first-line-h1: false
code-block-style:
  style: "fenced"
proper-names:
  names:
    [
      "API",
      "Azure",
      "Bitbucket",
      "Consul",
      "dicehub",
      "Debian",
      "DevOps",
      "Docker",
      "docker",
      "Figma",
      "Git",
      "GitHub",
      "GitLab",
      "GitLab Runner",
      "Google",
      "Grafana",
      "GraphQL",
      "Gzip",
      "Gmail",
      "Helm",
      "Ingress",
      "JavaScript",
      "Jaeger",
      "Kubernetes",
      "Let's Encrypt",
      "Markdown",
      "markdownlint",
      "Microsoft",
      "Minikube",
      "MinIO",
      "NGINX Ingress",
      "NGINX",
      "OAuth",
      "OAuth 2",
      "PgBouncer",
      "PostgreSQL",
      "Prometheus",
      "Python",
      "Redis",
      "Sentry",
      "SimOps",
      "Slack",
      "SMTP",
      "SSH",
      "TOML",
      "Trello",
      "TypeScript",
      "Twitter",
      "Ubuntu",
      "URL",
      "WebdriverIO",
      "WebAssembly",
      "yaml",
      "YAML",
      "YouTube",
    ]
  code_blocks: false
