site_name: dicehub Docs
site_description: dicehub Documentation
site_author: dicehub Team
site_url: https://docs.dicehub.com/
copyright: 'Copyright &copy; 2022 dicehub'
repo_url: ""

# Customization
theme:
  name: material
  custom_dir: theme/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: dicehub
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    # text: Poppins
    # text: Nunito Sans
    text: Roboto
    # text: Noto Sans
    code: Roboto Mono
  logo: assets/logo.svg
  favicon: 'assets/favicon.png'
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - navigation.indexes
    # - header.autohide
    # - toc.integrate
    - navigation.expand

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mermaid2:
      arguments:
        sequence:
          mirrorActors: false
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      # enable_creation_date: true
  - extra-sass
  - minify:
      minify_html: true
  # - redirects:
  #     redirect_maps:
  #       'terms.md': 'http://dicehub.com/terms'

extra:
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  # version:
  #   provider: mike
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dicehub
    - icon: fontawesome/brands/github
      link: https://github.com/dicehub

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: "#"
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  # - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  # - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:
      generic: true

# Site navigation in the side bar
nav:
  - Home: index.md
  # - Documentation: documentation/index.md
  - Guide:
    - guide/index.md
    - guide/quick_start.md
    - Essentials:
      - guide/essentials/index.md
      - guide/essentials/projects.md
      - guide/essentials/groups.md
      - guide/essentials/templates.md
      - guide/essentials/applications.md
      - guide/essentials/flows.md
    - Pricing:
      - guide/pricing/plans.md
    - UI / UX:
      - guide/ui/user_dashboard_ui.md
      - guide/ui/application_ui.md
    - Resources:
      - guide/resources/changelog.md
      - guide/resources/roadmap.md
  - Templates:
    - template/index.md
    - Meshing:
      - Hex-dominant mesher:
        - Overview: template/hex_dominant_mesher/index.md
        - Main Steps:
          - template/hex_dominant_mesher/geometries.md
          - template/hex_dominant_mesher/background_mesh.md
          - template/hex_dominant_mesher/material_point.md
          - template/hex_dominant_mesher/edges_refinement.md
          - template/hex_dominant_mesher/surface_refinement.md
          - template/hex_dominant_mesher/volume_refinement.md
          - template/hex_dominant_mesher/boundary_layers.md
          - template/hex_dominant_mesher/cell_zones.md
  # - User documentation:
  #   - User Docs: user/index.md
  #   - Features:
  #       Real-time collaboration: features/real-time-collaboration.md
  #       Scaling: features/scaling.md
  #       Visualization: features/visualization.md
  #       Optimization: features/optimization.md
  #   - Resources:
  #       Terms of service: https://dicehub.com/terms-of-service
  #       Privacy policy: https://dicehub.com/privacy-policy
  - Tutorials:
    - tutorials/index.md
  - Development:
    - Overview: development/index.md
    - Documentation:
      - development/documentation/index.md
  # - Design:
  #   - design/index.md
  # - Resources:
  #     - Overview: resources/index.md
  #     - Applications:
  #       - CFD: resources/cfd_software/index.md
  #       - Bio-Engineering: resources/bio_engineering/index.md
  - About:
      - FAQ: about/faq.md
      - Code of conduct: about/code_of_conduct.md
      - Terms of service: https://dicehub.com/terms-of-service
      - Privacy policy: https://dicehub.com/privacy-policy
